### PR TITLE
24 organize theme settings

### LINKED ISSUE #24: Organize theme settings
There are a lot of custom theme settings for the Lab theme, and the settings page is a little overwhelming right now. Some of the settings which are currently check boxes cannot be applied at the same time (but this isn't being validated).

I am proposing that the settings be separated into more field sets, and where it makes sense to use radios instead of check boxes for either/or settings.

This is a rough draft of how the form could be organized, with the Header Background Image settings displaying only if the "Header Background Image" toggle box is checked.
theme_settings

### PR DESCRIPTION
**Pull request by bspeare**
This resolves #24

### CODE REVIEW

**Comment by bspeare** [comment]
- I'm not seeing a transparency applied when the "transparency overlay option" is checked.  Is anyone else having this issue?
- I also think we might want to remove the default image in order to provide users with the default white theme based on the new theme settings configuration.  Or, do you recommend a way to install the theme with a default image uploaded into the main_image file field?

**Comment by adamdelaney** [comment]
Here are the classes that are being printed in my theme when the color overlay option is set to none: 
screen shot 2017-02-07 at 11 50 08 am

**Comment by genjohnson** [comment]
@adamdelaney I am not able to reproduce the issue you are having with the "no transparency" option still including an overlay. Are you testing with a newly-provisioned site? We've changed the name of all the theme settings...if you're testing on a site that was provisioned before the setting names changed I wonder if some old settings are still having an effect?

@bspeare I think removing the default image is the way to go.

**Comment by adamdelaney** [comment]
I was working off a pre-existing site. However I believe the theme settings all live in 1 variable so I feel like the variable names should not be a problem.

**Comment by adamdelaney** [comment]
Once I cleared cache this setting seems to be working properly. For some reason the .remove-opacity style was not being applied via css.

**Comment by adamdelaney** [comment]
Not trying to be picky but I noticed there were several functions declared in page.preprocess.inc. I feel like the html preprocessor could go in html.preprocess.inc and hook_css_alter could go in template.php

**Comment by bspeare** [comment]
That sounds good to me.  I moved the functions.  How do you usually resolve the merge conflicts with the generated css files?

**Comment by adamdelaney** [comment]
Thanks @bspeare. If it is css, you should re-compile the sass files and then commit your changes, since we know the updated css files will be the ones we need.

**Comment by adamdelaney** [comment]
Sorry I didn't explain myself very well. Checkout out master and pull, then checkout your feature branch and merge master. When you get a merge conflict simply re-compile and commit your changes. Be sure the css is the only files that have conflicts.

**Pull request merged**
